spring:
  gson:
    #手动添加的gson日期格式解析配置
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  #指定访问静态资源的前缀/static，会导致index.html欢迎页无法加载，而使用类配置则可以,后续研究下
  mvc:
    static-path-pattern: /static/**, /assets
  #自定义静态资源目录 项目classpath:/static
  resources:
    static-locations: classpath:/static/

  #spring数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #高版本 Mysql 驱动时，配置的 driver-class-name 不再是 com.mysql.jdbc.Driver，url 后面必须设置时区 serverTimezone
    url: jdbc:mysql://192.168.76.1:3306/chitchat?serverTimezone=Asia/Shanghai&useTimezone=true
    username: dev
    password: 123456
    #切换Druid数据源，引入spring-boot-starter-data-jdbc时默认为HikariDataSource数据源
    type: com.alibaba.druid.pool.DruidDataSource

  #jpa相关配置
  jpa:
    #jpa配置：在控制台显示Hibernate的sql(可选)
    show-sql: true
    #对应数据库(可选)
    database: mysql
    #自动生成数据库表（关键）
    hibernate:
      ddl-auto: update
#   boot:
#     admin:
#       client:
#         #配置adminServer的地址
#         url: http://localhost:8082


server:
  port: 8081
  #ssl配置
  ssl:
    key-store: classpath:key.p12
    key-alias: tomcathttps
    key-store-password: 123456
  #该配置添加项目前缀会导致获取ico图标失效
  servlet:
    context-path: /chitchat
  tomcat:
    uri-encoding: utf-8

#actuator重度依赖Jackson，使用gson可能会报错
management:
  endpoints:
    #关闭所有端点的配置
#    enabled-by-default: false
    web:
      #代表启用单独的url地址来监控 Spring Boot 应用，默认的路径是 /actuator/*
#      base-path: /monitor
#      path-mapping:
#        #将headth改为healths
#        health: healths
      exposure:
        #端点启用配置见上，该为暴露端点配置，"*"有特殊含义需加双引号
        #代表暴露全部监控，当然也可以配置需要开启的监控，如： include=beans,trace
        include: health,info,mappings,env,beans,shutdown
      #跨域相关支持
#      cors:
#        allowed-origins: https://localhost:8080
#        allowed-methods: GET,POST
  endpoint:
#    beans:
#      cache:
#        #配置beans端点的缓存时间为100秒，添加security后存在用户信息输入，端点信息不会缓存
#        time-to-live: 100s
    health:
      #always开启显示全部细节, never不显示细节, when_authorized只展示给认证用户roles: admin
      show-details: when_authorized
      roles: admin
    shutdown:
      #开启远程关闭应用端点，需post执行
      enabled: true

info:
  author:
    mame: ganmuren
    email: 1101543410@qq.com
  app:
    #@@引用maven的定义,改动时需clean ${}引用properties的定义
    java: @maven.compiler.source@
    port: ${server.port}


## 这里的配置属性只是基础配置，如需更多功能配置，请自行扩展
dubbo:
  application:
    #Dubbo 的应用名
    name: chitchat-provider
  registry:
    #Dubbo 使用的注册中心地址
    address: zookeeper://${zookeeper.address:192.168.76.1}:2181
  #Dubbo 协议信息
  protocol:
    name: dubbo
    port: -1

#spring log简单配置，使用logback-spring进行复杂配置
#logging:
#  level:
#    org.ganmuren: info #该包打印info及更高级别的日志
#  pattern: #日志打印规则
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
#  file: logs/chitchat.log
